package com.mukeshhh.myalculotar // Make sure this matches your package name

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.View
import android.widget.Button
import com.mukeshhh.myalculotar.databinding.ActivityMainBinding // This import is generated by View Binding
import org.mariuszgromada.math.mxparser.Expression

class MainActivity : AppCompatActivity() {

    // A variable to hold the binding object, which gives us access to our UI elements.
    private lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // This sets up view binding for use.
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
    }

    /**
     * This function is called when any number (0-9) or operator (+, -, *, /) button is clicked.
     */
    fun onDigit(view: View) {
        // We add the text of the button that was clicked to our display.
        binding.tvInput.append((view as Button).text)
    }

    /**
     * This function is called when the 'C' (Clear) button is clicked.
     */
    fun onClear(view: View) {
        // We set the display text to be empty.
        binding.tvInput.text = ""
    }

    /**
     * This function is called when the '=' (Equals) button is clicked.
     */
    fun onEqual(view: View) {
        // We use a try-catch block to prevent the app from crashing if the math expression is invalid.
        try {
            // Get the expression from the TextView as a string.
            val expressionText = binding.tvInput.text.toString()

            // Use the mxparser library to create an Expression object.
            val expression = Expression(expressionText)

            // Calculate the result.
            val result = expression.calculate()

            // If the result is a valid number, display it.
            if (!result.isNaN()) {
                binding.tvInput.text = result.toString()
            } else {
                // If the expression is invalid (e.g., "5/"), show an error.
                binding.tvInput.text = "Error"
            }
        } catch (e: Exception) {
            // If any other error happens, show "Error".
            binding.tvInput.text = "Error"
        }
    }
}